version: '3.8'
services:
  php:
    build:
      context: build/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html/app
  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html/app
    working_dir: /var/www/html/app
  web:
    build:
      context: build/nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/public:/var/www/html/app/public